In [19]:
from tensorflow.keras.preprocessing.text import hashing_trick
import numpy as np
import pandas as pd

In [12]:
vocab_size = 10000
text = "This is an example"
encoded = hashing_trick(text, vocab_size, hash_function='md5')
print(encoded)


[3956, 6204, 1557, 6764]


In [13]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [14]:
hashed_data = [hashing_trick(word, vocab_size, hash_function='md5')for word in sent]

In [15]:
hashed_data

[[5001, 7898, 7566, 7150],
 [5001, 7898, 7566, 3356],
 [5001, 1306, 7566, 9309],
 [8765, 567, 1181, 3270, 7123],
 [8765, 567, 1181, 3270, 6634],
 [983, 5001, 3362, 7566, 661],
 [976, 8912, 1982, 3270]]

In [20]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
sent_length = 8
embedded_data = pad_sequences(hashed_data,padding='pre', maxlen=sent_length)
print(embedded_data)

[[   0    0    0    0 5001 7898 7566 7150]
 [   0    0    0    0 5001 7898 7566 3356]
 [   0    0    0    0 5001 1306 7566 9309]
 [   0    0    0 8765  567 1181 3270 7123]
 [   0    0    0 8765  567 1181 3270 6634]
 [   0    0    0  983 5001 3362 7566  661]
 [   0    0    0    0  976 8912 1982 3270]]


In [23]:
#feature representaion 
dim = 10

In [25]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [26]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
